Repository Dominicod/futbol, pull requests merged in 2022-07, with the labels that each got.

#34 Add from_csv method to StatTracker
  lib/stat_tracker.rb
  runner.rb
  spec/spec_helper.rb
Labels: bug

#36 Team statistics
  data/fixture_data_team_satistics/fixture_game_teams.csv
  data/fixture_data_team_satistics/fixture_games.csv
  lib/stat_tracker.rb
  lib/team_statistics.rb
  spec/team_statistics_spec.rb
Labels: enhancement

#37 Feat/league statistics
  data/fixture_data_league_statistics/dummy_game_teams.csv
  lib/league_statistics.rb
  spec/league_statistics_spec.rb
Labels: enhancement

#38 feat: establish conventions, update methods and classes to work together
  .DS_Store
  data/fixture_data_league_statistics/dummy_game_teams.csv
  data/fixture_data_team_satistics/fixture_game_teams.csv
  data/fixture_data_team_satistics/fixture_games.csv
  fixtures/fixture_data_game_statistics/game.csv
  lib/game.rb
  lib/game_statistics.rb
  lib/league_statistics.rb
  lib/stat_tracker.rb
  lib/team_statistics.rb
  spec/game_spec.rb
  spec/league_statistics_spec.rb
  spec/stat_tracker_spec.rb
  spec/stat_tracker_spec_1.rb
  spec/team_statistics_spec.rb
Labels: enhancement

#42 Feat/league statistics
  lib/league_statistics.rb
  spec/league_statistics_spec.rb
Labels: enhancement

#43 feat: created a module to sort and return a unique seasons hash
  lib/game.rb
  lib/uniquable.rb
Labels: enhancement

#47 Seasonstats fix
  data/games.csv
  lib/season_statistics.rb
  spec/season_statistics_spec.rb
Labels: bug, enhancement
